services:
  postgres:
    image: postgres:16-alpine
    container_name: pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: smartlife_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    shm_size: 64m
    mem_limit: 96m

  backend:
    build: .
    container_name: smartlife
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smartlife_db
    depends_on:
      - postgres
    mem_limit: 320m

volumes:
  pgdata: