#version: '3.9'
#
#services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    platform: linux/amd64
#    container_name: spring-boot-app
#    restart: unless-stopped
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=prod
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/smartlife
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#    depends_on:
#      db:
#        condition: service_healthy
#    networks:
#      - app-network
#
#  db:
#    image: postgres:15-alpine
#    platform: linux/amd64
#    container_name: postgres-db
#    restart: unless-stopped
#    environment:
#      POSTGRES_DB: smartlife
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#
#    networks:
#      - app-network
#
#volumes:
#  postgres-data:
#
#networks:
#  app-network:
#    driver: bridge