spring:
  application:
    name: smartlife

#  datasource:
#    url: jdbc:postgresql://shortline.proxy.rlwy.net:20643/railway
#    username: postgres
#    password: FnSGTDttyQNPhjDWJHjvqraSewYTUiZW
#    driver-class-name: org.postgresql.Driver

#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/smartlife
#    username: postgres
#    password: postgres

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:smartlife;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  address: 0.0.0.0
